spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/todo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'com-givejeong-todo-study-portfolio-app-spring-jpa-security-react-jwt-secret-key'|base64
  secret: Y29tLWdpdmVqZW9uZy10b2RvLXN0dWR5LXBvcnRmb2xpby1hcHAtc3ByaW5nLWpwYS1zZWN1cml0eS1yZWFjdC1qd3Qtc2VjcmV0LWtleQ==
  token-validity-in-seconds: 600000